# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c6dd4bfae612787df84e6239e5f0f3ad0b3ce2665d21c28c707165a568f3b0cfec2e860f03c1734777d380fb359243e1e6340f1e262d8ef5aaa7148145990cc

test:
  secret_key_base: 0aa8980e96240ebac913f73c86cf3f215c3b5be8b1356742b0cadf80bbde0f48a4467215a32e04512a6def0275eba45bc795a16d304c5709ebf72eb87b1c39e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
